# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import datetime
from django.utils.timezone import utc
from django.conf import settings
import uuidfield.fields


class Migration(migrations.Migration):

    replaces = [(b'quickbooks', '0001_initial'), (b'quickbooks', '0002_auto_20141231_1734'), (b'quickbooks', '0003_l_qbaccount_qbcheck_qbestimate_qbinvoice'), (b'quickbooks', '0004_delete_l'), (b'quickbooks', '0005_auto_20150206_1552'), (b'quickbooks', '0006_auto_20150211_0408'), (b'quickbooks', '0007_auto_20150212_2108'), (b'quickbooks', '0008_qbitem'), (b'quickbooks', '0009_auto_20150415_2237'), (b'quickbooks', '0010_qbbill_txn_id'), (b'quickbooks', '0011_auto_20150417_0040'), (b'quickbooks', '0012_auto_20150421_1705'), (b'quickbooks', '0013_qbitempayment'), (b'quickbooks', '0014_auto_20150422_1533'), (b'quickbooks', '0015_qbbill_is_paid'), (b'quickbooks', '0016_auto_20150428_2216'), (b'quickbooks', '0017_qbitem_sales_or_purchase')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageQue',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(default=b'Query', max_length=2500)),
                ('description', models.TextField(null=True, blank=True)),
                ('message', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('repeat', models.BooleanField(default=False)),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
                ('last_accessed', models.TimeField(default=datetime.datetime(2014, 12, 31, 17, 34, 9, 514976, tzinfo=utc), auto_now=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='QBCustomer',
            fields=[
                ('state', models.CharField(max_length=2500, null=True, blank=True)),
                ('notes', models.CharField(max_length=2500, null=True, blank=True)),
                ('postal_code', models.CharField(max_length=2500, null=True, blank=True)),
                ('middle_name', models.CharField(max_length=2500, null=True, blank=True)),
                ('phone', models.CharField(max_length=2500, null=True, blank=True)),
                ('fax', models.CharField(max_length=2500, null=True, blank=True)),
                ('city', models.CharField(max_length=2500, null=True, blank=True)),
                ('contact', models.CharField(max_length=2500, null=True, blank=True)),
                ('account_number', models.CharField(max_length=2500, null=True, blank=True)),
                ('full_name', models.CharField(max_length=2500, null=True, blank=True)),
                ('company_name', models.CharField(max_length=2500, null=True, blank=True)),
                ('name', models.CharField(max_length=2500, null=True, blank=True)),
                ('ship_address', models.CharField(max_length=2500, null=True, blank=True)),
                ('sublevel', models.CharField(max_length=2500, null=True, blank=True)),
                ('alt_phone', models.CharField(max_length=2500, null=True, blank=True)),
                ('first_name', models.CharField(max_length=2500, null=True, blank=True)),
                ('last_name', models.CharField(max_length=2500, null=True, blank=True)),
                ('customer_type_ref', models.CharField(max_length=2500, null=True, blank=True)),
                ('total_balance', models.CharField(max_length=2500, null=True, blank=True)),
                ('bill_address', models.CharField(max_length=2500, null=True, blank=True)),
                ('addr2', models.CharField(max_length=2500, null=True, blank=True)),
                ('item_sales_tax_ref', models.CharField(max_length=2500, null=True, blank=True)),
                ('alt_contact', models.CharField(max_length=2500, null=True, blank=True)),
                ('addr4', models.CharField(max_length=2500, null=True, blank=True)),
                ('is_active', models.CharField(max_length=2500, null=True, blank=True)),
                ('addr3', models.CharField(max_length=2500, null=True, blank=True)),
                ('list_id', models.CharField(max_length=2500, serialize=False, primary_key=True)),
                ('addr1', models.CharField(max_length=2500, null=True, blank=True)),
                ('job_status', models.CharField(max_length=2500, null=True, blank=True)),
                ('edit_sequence', models.CharField(max_length=2500, null=True, blank=True)),
                ('time_created', models.CharField(max_length=2500, null=True, blank=True)),
                ('time_modified', models.CharField(max_length=2500, null=True, blank=True)),
                ('sales_tax_code_ref', models.CharField(max_length=2500, null=True, blank=True)),
                ('balance', models.CharField(max_length=2500, null=True, blank=True)),
                ('terms_ref', models.CharField(max_length=2500, null=True, blank=True)),
                ('salutation', models.CharField(max_length=2500, null=True, blank=True)),
                ('email', models.CharField(max_length=2500, null=True, blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='QWCTicket',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('ticket', uuidfield.fields.UUIDField(unique=True, max_length=32, editable=False, blank=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ReceiveResponse',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('response', models.TextField()),
                ('processed', models.BooleanField(default=False)),
                ('ticket', models.ForeignKey(to='quickbooks.QWCTicket')),
                ('name', models.CharField(default=b'', max_length=2500, null=True, blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('company_file', models.CharField(default=b'', max_length=2500, blank=True)),
                ('major_version', models.CharField(default=b'', max_length=2500, blank=True)),
                ('minor_version', models.CharField(default=b'', max_length=2500, blank=True)),
                ('user', models.OneToOneField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='QBAccount',
            fields=[
                ('cash_flow_classification', models.CharField(max_length=2500, null=True, blank=True)),
                ('account_number', models.CharField(max_length=2500, null=True, blank=True)),
                ('special_account_type', models.CharField(max_length=2500, null=True, blank=True)),
                ('desc', models.CharField(max_length=2500, null=True, blank=True)),
                ('time_modified', models.CharField(max_length=2500, null=True, blank=True)),
                ('edit_sequence', models.CharField(max_length=2500, null=True, blank=True)),
                ('total_balance', models.CharField(max_length=2500, null=True, blank=True)),
                ('is_active', models.CharField(max_length=2500, null=True, blank=True)),
                ('list_id', models.CharField(max_length=2500, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=2500, null=True, blank=True)),
                ('full_name', models.CharField(max_length=2500, null=True, blank=True)),
                ('time_created', models.CharField(max_length=2500, null=True, blank=True)),
                ('sublevel', models.CharField(max_length=2500, null=True, blank=True)),
                ('account_type', models.CharField(max_length=2500, null=True, blank=True)),
                ('parent_ref', models.CharField(max_length=2500, null=True, blank=True)),
                ('balance', models.CharField(max_length=2500, null=True, blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='QBCheck',
            fields=[
                ('time_modified', models.CharField(max_length=2500, null=True, blank=True)),
                ('account_ref', models.CharField(max_length=2500, null=True, blank=True)),
                ('txn_date', models.CharField(max_length=2500, null=True, blank=True)),
                ('city', models.CharField(max_length=2500, null=True, blank=True)),
                ('addr1', models.CharField(max_length=2500, null=True, blank=True)),
                ('list_id', models.CharField(max_length=2500, serialize=False, primary_key=True)),
                ('country', models.CharField(max_length=2500, null=True, blank=True)),
                ('amount', models.CharField(max_length=2500, null=True, blank=True)),
                ('is_to_be_printed', models.CharField(max_length=2500, null=True, blank=True)),
                ('addr2', models.CharField(max_length=2500, null=True, blank=True)),
                ('memo', models.CharField(max_length=2500, null=True, blank=True)),
                ('addr4', models.CharField(max_length=2500, null=True, blank=True)),
                ('postal_code', models.CharField(max_length=2500, null=True, blank=True)),
                ('addr3', models.CharField(max_length=2500, null=True, blank=True)),
                ('ref_number', models.CharField(max_length=2500, null=True, blank=True)),
                ('address', models.CharField(max_length=2500, null=True, blank=True)),
                ('time_created', models.CharField(max_length=2500, null=True, blank=True)),
                ('full_name', models.CharField(max_length=2500, null=True, blank=True)),
                ('edit_sequence', models.CharField(max_length=2500, null=True, blank=True)),
                ('state', models.CharField(max_length=2500, null=True, blank=True)),
                ('payee_entity_ref', models.CharField(max_length=2500, null=True, blank=True)),
                ('txn_number', models.CharField(max_length=2500, null=True, blank=True)),
                ('txn_id', models.CharField(max_length=2500, null=True, blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='QBEstimate',
            fields=[
                ('bill_address', models.CharField(max_length=2500, null=True, blank=True)),
                ('ref_number', models.CharField(max_length=2500, null=True, blank=True)),
                ('full_name', models.CharField(max_length=2500, null=True, blank=True)),
                ('addr1', models.CharField(max_length=2500, null=True, blank=True)),
                ('txn_date', models.CharField(max_length=2500, null=True, blank=True)),
                ('customer_ref', models.CharField(max_length=2500, null=True, blank=True)),
                ('customer_sales_tax_code_ref', models.CharField(max_length=2500, null=True, blank=True)),
                ('addr2', models.CharField(max_length=2500, null=True, blank=True)),
                ('addr4', models.CharField(max_length=2500, null=True, blank=True)),
                ('txn_number', models.CharField(max_length=2500, null=True, blank=True)),
                ('total_amount', models.CharField(max_length=2500, null=True, blank=True)),
                ('time_modified', models.CharField(max_length=2500, null=True, blank=True)),
                ('memo', models.CharField(max_length=2500, null=True, blank=True)),
                ('postal_code', models.CharField(max_length=2500, null=True, blank=True)),
                ('due_date', models.CharField(max_length=2500, null=True, blank=True)),
                ('addr3', models.CharField(max_length=2500, null=True, blank=True)),
                ('subtotal', models.CharField(max_length=2500, null=True, blank=True)),
                ('item_sales_tax_ref', models.CharField(max_length=2500, null=True, blank=True)),
                ('sales_tax_percentage', models.CharField(max_length=2500, null=True, blank=True)),
                ('txn_id', models.CharField(max_length=2500, null=True, blank=True)),
                ('class_ref', models.CharField(max_length=2500, null=True, blank=True)),
                ('city', models.CharField(max_length=2500, null=True, blank=True)),
                ('sales_tax_total', models.CharField(max_length=2500, null=True, blank=True)),
                ('list_id', models.CharField(max_length=2500, serialize=False, primary_key=True)),
                ('state', models.CharField(max_length=2500, null=True, blank=True)),
                ('edit_sequence', models.CharField(max_length=2500, null=True, blank=True)),
                ('time_created', models.CharField(max_length=2500, null=True, blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='QBInvoice',
            fields=[
                ('addr1', models.CharField(max_length=2500, null=True, blank=True)),
                ('addr3', models.CharField(max_length=2500, null=True, blank=True)),
                ('sales_tax_percentage', models.CharField(max_length=2500, null=True, blank=True)),
                ('full_name', models.CharField(max_length=2500, null=True, blank=True)),
                ('time_modified', models.CharField(max_length=2500, null=True, blank=True)),
                ('applied_amount', models.CharField(max_length=2500, null=True, blank=True)),
                ('ship_date', models.CharField(max_length=2500, null=True, blank=True)),
                ('customer_sales_tax_code_ref', models.CharField(max_length=2500, null=True, blank=True)),
                ('po_number', models.CharField(max_length=2500, null=True, blank=True)),
                ('addr2', models.CharField(max_length=2500, null=True, blank=True)),
                ('item_sales_tax_ref', models.CharField(max_length=2500, null=True, blank=True)),
                ('ship_address', models.CharField(max_length=2500, null=True, blank=True)),
                ('bill_address', models.CharField(max_length=2500, null=True, blank=True)),
                ('txn_number', models.CharField(max_length=2500, null=True, blank=True)),
                ('sales_tax_total', models.CharField(max_length=2500, null=True, blank=True)),
                ('is_paid', models.CharField(max_length=2500, null=True, blank=True)),
                ('suggested_discount_amount', models.CharField(max_length=2500, null=True, blank=True)),
                ('ref_number', models.CharField(max_length=2500, null=True, blank=True)),
                ('class_ref', models.CharField(max_length=2500, null=True, blank=True)),
                ('txn_date', models.CharField(max_length=2500, null=True, blank=True)),
                ('addr4', models.CharField(max_length=2500, null=True, blank=True)),
                ('postal_code', models.CharField(max_length=2500, null=True, blank=True)),
                ('ar_account_ref', models.CharField(max_length=2500, null=True, blank=True)),
                ('is_finance_charge', models.CharField(max_length=2500, null=True, blank=True)),
                ('is_to_be_printed', models.CharField(max_length=2500, null=True, blank=True)),
                ('suggested_discount_date', models.CharField(max_length=2500, null=True, blank=True)),
                ('time_created', models.CharField(max_length=2500, null=True, blank=True)),
                ('memo', models.CharField(max_length=2500, null=True, blank=True)),
                ('terms_ref', models.CharField(max_length=2500, null=True, blank=True)),
                ('customer_ref', models.CharField(max_length=2500, null=True, blank=True)),
                ('city', models.CharField(max_length=2500, null=True, blank=True)),
                ('due_date', models.CharField(max_length=2500, null=True, blank=True)),
                ('txn_id', models.CharField(max_length=2500, null=True, blank=True)),
                ('balance_remaining', models.CharField(max_length=2500, null=True, blank=True)),
                ('subtotal', models.CharField(max_length=2500, null=True, blank=True)),
                ('state', models.CharField(max_length=2500, null=True, blank=True)),
                ('list_id', models.CharField(max_length=2500, serialize=False, primary_key=True)),
                ('is_pending', models.CharField(max_length=2500, null=True, blank=True)),
                ('edit_sequence', models.CharField(max_length=2500, null=True, blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='QBItem',
            fields=[
                ('item_desc', models.CharField(max_length=2500, null=True, blank=True)),
                ('item_group_line', models.CharField(max_length=2500, null=True, blank=True)),
                ('sales_tax_code_ref', models.CharField(max_length=2500, null=True, blank=True)),
                ('edit_sequence', models.CharField(max_length=2500, null=True, blank=True)),
                ('average_cost', models.CharField(max_length=2500, null=True, blank=True)),
                ('tax_vendor_ref', models.CharField(max_length=2500, null=True, blank=True)),
                ('tax_rate', models.CharField(max_length=2500, null=True, blank=True)),
                ('quantity_on_order', models.CharField(max_length=2500, null=True, blank=True)),
                ('sales_and_purchase', models.CharField(max_length=2500, null=True, blank=True)),
                ('purchase_cost', models.CharField(max_length=2500, null=True, blank=True)),
                ('list_id', models.CharField(max_length=2500, serialize=False, primary_key=True)),
                ('cogs_account_ref', models.CharField(max_length=2500, null=True, blank=True)),
                ('discount_rate_percent', models.CharField(max_length=2500, null=True, blank=True)),
                ('reorder_point', models.CharField(max_length=2500, null=True, blank=True)),
                ('purchase_desc', models.CharField(max_length=2500, null=True, blank=True)),
                ('pref_vendor_ref', models.CharField(max_length=2500, null=True, blank=True)),
                ('quantity_on_sales_order', models.CharField(max_length=2500, null=True, blank=True)),
                ('name', models.CharField(max_length=2500, null=True, blank=True)),
                ('sublevel', models.CharField(max_length=2500, null=True, blank=True)),
                ('income_account_ref', models.CharField(max_length=2500, null=True, blank=True)),
                ('quantity_on_hand', models.CharField(max_length=2500, null=True, blank=True)),
                ('discount_rate', models.CharField(max_length=2500, null=True, blank=True)),
                ('sales_or_purchase', models.CharField(max_length=2500, null=True, blank=True)),
                ('account_ref', models.CharField(max_length=2500, null=True, blank=True)),
                ('is_print_items_in_group', models.CharField(max_length=2500, null=True, blank=True)),
                ('time_created', models.CharField(max_length=2500, null=True, blank=True)),
                ('sales_desc', models.CharField(max_length=2500, null=True, blank=True)),
                ('asset_account_ref', models.CharField(max_length=2500, null=True, blank=True)),
                ('time_modified', models.CharField(max_length=2500, null=True, blank=True)),
                ('parent_ref', models.CharField(max_length=2500, null=True, blank=True)),
                ('full_name', models.CharField(max_length=2500, null=True, blank=True)),
                ('sales_price', models.CharField(max_length=2500, null=True, blank=True)),
                ('is_active', models.CharField(max_length=2500, null=True, blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ExpenseLineAdd',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('amount', models.CharField(max_length=2500, null=True, blank=True)),
                ('memo', models.CharField(max_length=2500, null=True, blank=True)),
                ('account_ref', models.ForeignKey(blank=True, to='quickbooks.QBAccount', null=True)),
                ('customer_ref', models.ForeignKey(blank=True, to='quickbooks.QBCustomer', null=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='QBBill',
            fields=[
                ('txn_date', models.CharField(max_length=255, null=True, blank=True)),
                ('due_date', models.CharField(max_length=255, null=True, blank=True)),
                ('ref_number', models.CharField(max_length=2500, null=True, blank=True)),
                ('memo', models.CharField(max_length=2500, null=True, blank=True)),
                ('exchange_rate', models.CharField(max_length=2500, null=True, blank=True)),
                ('txn_id', models.CharField(max_length=2500, serialize=False, primary_key=True)),
                ('is_pending', models.CharField(max_length=2500, null=True, blank=True)),
                ('edit_sequence', models.CharField(max_length=2500, null=True, blank=True)),
                ('expense_line_add', models.ManyToManyField(to=b'quickbooks.ExpenseLineAdd', null=True, blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='QBVendor',
            fields=[
                ('name', models.CharField(max_length=2500, null=True, blank=True)),
                ('first_name', models.CharField(max_length=2500, null=True, blank=True)),
                ('middle_name', models.CharField(max_length=2500, null=True, blank=True)),
                ('last_name', models.CharField(max_length=2500, null=True, blank=True)),
                ('full_name', models.CharField(max_length=2500, null=True, blank=True)),
                ('company_name', models.CharField(max_length=2500, null=True, blank=True)),
                ('salutation', models.CharField(max_length=2500, null=True, blank=True)),
                ('job_title', models.CharField(max_length=2500, null=True, blank=True)),
                ('phone', models.CharField(max_length=2500, null=True, blank=True)),
                ('alt_phone', models.CharField(max_length=2500, null=True, blank=True)),
                ('fax', models.CharField(max_length=2500, null=True, blank=True)),
                ('email', models.CharField(max_length=2500, null=True, blank=True)),
                ('contact', models.CharField(max_length=2500, null=True, blank=True)),
                ('alt_contact', models.CharField(max_length=2500, null=True, blank=True)),
                ('notes', models.CharField(max_length=2500, null=True, blank=True)),
                ('account_number', models.CharField(max_length=2500, null=True, blank=True)),
                ('credit_limit', models.CharField(max_length=2500, null=True, blank=True)),
                ('vendor_tax_ident', models.CharField(max_length=2500, null=True, blank=True)),
                ('list_id', models.CharField(max_length=2500, serialize=False, primary_key=True)),
                ('is_pending', models.CharField(max_length=2500, null=True, blank=True)),
                ('edit_sequence', models.CharField(max_length=2500, null=True, blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='qbbill',
            name='vendor_ref',
            field=models.ForeignKey(blank=True, to='quickbooks.QBVendor', null=True),
            preserve_default=True,
        ),
        migrations.CreateModel(
            name='QBInvoiceLineAdd',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('desc', models.CharField(max_length=2500, null=True, blank=True)),
                ('quantity', models.CharField(max_length=2500, null=True, blank=True)),
                ('unit_of_measure', models.CharField(max_length=2500, null=True, blank=True)),
                ('amount', models.CharField(max_length=2500, null=True, blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='qbinvoice',
            name='invoice_line_add',
            field=models.ManyToManyField(to=b'quickbooks.QBInvoiceLineAdd', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.CreateModel(
            name='QBEmployee',
            fields=[
                ('list_id', models.CharField(max_length=2500, serialize=False, primary_key=True)),
                ('first_name', models.CharField(max_length=2500, null=True, blank=True)),
                ('middle_name', models.CharField(max_length=2500, null=True, blank=True)),
                ('last_name', models.CharField(max_length=2500, null=True, blank=True)),
                ('full_name', models.CharField(max_length=2500, null=True, blank=True)),
                ('name', models.CharField(max_length=2500, null=True, blank=True)),
                ('notes', models.CharField(max_length=2500, null=True, blank=True)),
                ('phone', models.CharField(max_length=2500, null=True, blank=True)),
                ('fax', models.CharField(max_length=2500, null=True, blank=True)),
                ('city', models.CharField(max_length=2500, null=True, blank=True)),
                ('contact', models.CharField(max_length=2500, null=True, blank=True)),
                ('account_number', models.CharField(max_length=2500, null=True, blank=True)),
                ('company_name', models.CharField(max_length=2500, null=True, blank=True)),
                ('is_active', models.CharField(max_length=2500, null=True, blank=True)),
                ('edit_sequence', models.CharField(max_length=2500, null=True, blank=True)),
                ('time_created', models.CharField(max_length=2500, null=True, blank=True)),
                ('time_modified', models.CharField(max_length=2500, null=True, blank=True)),
                ('salutation', models.CharField(max_length=2500, null=True, blank=True)),
                ('email', models.CharField(max_length=2500, null=True, blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='QBItemLineAdd',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('serial_number', models.CharField(max_length=255, null=True, blank=True)),
                ('lot_number', models.CharField(max_length=255, null=True, blank=True)),
                ('desc', models.CharField(max_length=255, null=True, blank=True)),
                ('quantity', models.CharField(max_length=255, null=True, blank=True)),
                ('amount', models.CharField(max_length=2500, null=True, blank=True)),
                ('cost', models.CharField(max_length=255, null=True, blank=True)),
                ('unit_of_measure', models.CharField(max_length=255, null=True, blank=True)),
                ('memo', models.CharField(max_length=2500, null=True, blank=True)),
                ('customer_ref', models.ForeignKey(blank=True, to='quickbooks.QBCustomer', null=True)),
                ('item_ref', models.ForeignKey(blank=True, to='quickbooks.QBItem', null=True)),
                ('sales_rep_ref', models.ForeignKey(blank=True, to='quickbooks.QBEmployee', null=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='qbbill',
            name='item_line_add',
            field=models.ManyToManyField(to=b'quickbooks.QBItemLineAdd', null=True, blank=True),
            preserve_default=True,
        ),
        migrations.CreateModel(
            name='QBItemPayment',
            fields=[
                ('list_id', models.CharField(max_length=2500, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=255, null=True, blank=True)),
                ('item_desc', models.CharField(max_length=255, null=True, blank=True)),
                ('edit_sequence', models.CharField(max_length=2500, null=True, blank=True)),
                ('time_created', models.CharField(max_length=2500, null=True, blank=True)),
                ('time_modified', models.CharField(max_length=2500, null=True, blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='qbbill',
            name='is_paid',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.CreateModel(
            name='QBSalesOrPurchase',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('price', models.CharField(max_length=2500, null=True, blank=True)),
                ('account_ref', models.ForeignKey(blank=True, to='quickbooks.QBAccount', null=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.RemoveField(
            model_name='qbitem',
            name='sales_or_purchase',
        ),
        migrations.AddField(
            model_name='qbitem',
            name='sales_or_purchase',
            field=models.ForeignKey(blank=True, to='quickbooks.QBSalesOrPurchase', null=True),
            preserve_default=True,
        ),
    ]
