# Generated by Django 3.0.6 on 2020-06-20 17:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageque',
            name='name',
            field=models.CharField(default='Query', max_length=2500),
        ),
        migrations.AlterField(
            model_name='qbbill',
            name='expense_line_add',
            field=models.ManyToManyField(blank=True, to='quickbooks.ExpenseLineAdd'),
        ),
        migrations.AlterField(
            model_name='qbbill',
            name='item_line_add',
            field=models.ManyToManyField(blank=True, to='quickbooks.QBItemLineAdd'),
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='invoice_line_add',
            field=models.ManyToManyField(blank=True, to='quickbooks.QBInvoiceLineAdd'),
        ),
        migrations.AlterField(
            model_name='qwcmessage',
            name='request_type',
            field=models.CharField(choices=[('closeConnection', 'Close Connection'), ('authenticate', 'Authenticate'), ('receiveResponseXML', 'Receive Request'), ('sendRequestXML', 'Send Request'), ('connectionError', 'Connection Error'), ('getInteractiveUrl', 'Get Interactive URL'), ('getLastError', 'Get Last Error'), ('serverVersion', 'Server Version'), ('clientVersion', 'Client Version')], max_length=255),
        ),
        migrations.AlterField(
            model_name='qwcticket',
            name='ticket',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
        migrations.AlterField(
            model_name='receiveresponse',
            name='name',
            field=models.CharField(blank=True, default='', max_length=2500, null=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
