# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks', '0002_auto_20141231_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='L',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, verbose_name='ID', serialize=False)),
                ('name', models.CharField(null=True, blank=True, max_length=255)),
                ('special_account_type', models.CharField(null=True, blank=True, max_length=255)),
                ('sublevel', models.CharField(null=True, blank=True, max_length=255)),
                ('time_created', models.CharField(null=True, blank=True, max_length=255)),
                ('time_modified', models.CharField(null=True, blank=True, max_length=255)),
                ('parent_ref', models.CharField(null=True, blank=True, max_length=255)),
                ('is_active', models.CharField(null=True, blank=True, max_length=255)),
                ('edit_sequence', models.CharField(null=True, blank=True, max_length=255)),
                ('account_type', models.CharField(null=True, blank=True, max_length=255)),
                ('cash_flow_classification', models.CharField(null=True, blank=True, max_length=255)),
                ('list_id', models.CharField(null=True, blank=True, max_length=255)),
                ('full_name', models.CharField(null=True, blank=True, max_length=255)),
                ('balance', models.CharField(null=True, blank=True, max_length=255)),
                ('account_number', models.CharField(null=True, blank=True, max_length=255)),
                ('total_balance', models.CharField(null=True, blank=True, max_length=255)),
                ('desc', models.CharField(null=True, blank=True, max_length=255)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='QBAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, verbose_name='ID', serialize=False)),
                ('cash_flow_classification', models.CharField(null=True, blank=True, max_length=255)),
                ('account_number', models.CharField(null=True, blank=True, max_length=255)),
                ('special_account_type', models.CharField(null=True, blank=True, max_length=255)),
                ('desc', models.CharField(null=True, blank=True, max_length=255)),
                ('time_modified', models.CharField(null=True, blank=True, max_length=255)),
                ('edit_sequence', models.CharField(null=True, blank=True, max_length=255)),
                ('total_balance', models.CharField(null=True, blank=True, max_length=255)),
                ('is_active', models.CharField(null=True, blank=True, max_length=255)),
                ('list_id', models.CharField(null=True, blank=True, max_length=255)),
                ('name', models.CharField(null=True, blank=True, max_length=255)),
                ('full_name', models.CharField(null=True, blank=True, max_length=255)),
                ('time_created', models.CharField(null=True, blank=True, max_length=255)),
                ('sublevel', models.CharField(null=True, blank=True, max_length=255)),
                ('account_type', models.CharField(null=True, blank=True, max_length=255)),
                ('parent_ref', models.CharField(null=True, blank=True, max_length=255)),
                ('balance', models.CharField(null=True, blank=True, max_length=255)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='QBCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, verbose_name='ID', serialize=False)),
                ('time_modified', models.CharField(null=True, blank=True, max_length=255)),
                ('account_ref', models.CharField(null=True, blank=True, max_length=255)),
                ('txn_date', models.CharField(null=True, blank=True, max_length=255)),
                ('city', models.CharField(null=True, blank=True, max_length=255)),
                ('addr1', models.CharField(null=True, blank=True, max_length=255)),
                ('list_id', models.CharField(null=True, blank=True, max_length=255)),
                ('country', models.CharField(null=True, blank=True, max_length=255)),
                ('amount', models.CharField(null=True, blank=True, max_length=255)),
                ('is_to_be_printed', models.CharField(null=True, blank=True, max_length=255)),
                ('addr2', models.CharField(null=True, blank=True, max_length=255)),
                ('memo', models.CharField(null=True, blank=True, max_length=255)),
                ('addr4', models.CharField(null=True, blank=True, max_length=255)),
                ('postal_code', models.CharField(null=True, blank=True, max_length=255)),
                ('addr3', models.CharField(null=True, blank=True, max_length=255)),
                ('ref_number', models.CharField(null=True, blank=True, max_length=255)),
                ('address', models.CharField(null=True, blank=True, max_length=255)),
                ('time_created', models.CharField(null=True, blank=True, max_length=255)),
                ('full_name', models.CharField(null=True, blank=True, max_length=255)),
                ('edit_sequence', models.CharField(null=True, blank=True, max_length=255)),
                ('state', models.CharField(null=True, blank=True, max_length=255)),
                ('payee_entity_ref', models.CharField(null=True, blank=True, max_length=255)),
                ('txn_number', models.CharField(null=True, blank=True, max_length=255)),
                ('txn_id', models.CharField(null=True, blank=True, max_length=255)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='QBEstimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, verbose_name='ID', serialize=False)),
                ('bill_address', models.CharField(null=True, blank=True, max_length=255)),
                ('ref_number', models.CharField(null=True, blank=True, max_length=255)),
                ('full_name', models.CharField(null=True, blank=True, max_length=255)),
                ('addr1', models.CharField(null=True, blank=True, max_length=255)),
                ('txn_date', models.CharField(null=True, blank=True, max_length=255)),
                ('customer_ref', models.CharField(null=True, blank=True, max_length=255)),
                ('customer_sales_tax_code_ref', models.CharField(null=True, blank=True, max_length=255)),
                ('addr2', models.CharField(null=True, blank=True, max_length=255)),
                ('addr4', models.CharField(null=True, blank=True, max_length=255)),
                ('txn_number', models.CharField(null=True, blank=True, max_length=255)),
                ('total_amount', models.CharField(null=True, blank=True, max_length=255)),
                ('time_modified', models.CharField(null=True, blank=True, max_length=255)),
                ('memo', models.CharField(null=True, blank=True, max_length=255)),
                ('postal_code', models.CharField(null=True, blank=True, max_length=255)),
                ('due_date', models.CharField(null=True, blank=True, max_length=255)),
                ('addr3', models.CharField(null=True, blank=True, max_length=255)),
                ('subtotal', models.CharField(null=True, blank=True, max_length=255)),
                ('item_sales_tax_ref', models.CharField(null=True, blank=True, max_length=255)),
                ('sales_tax_percentage', models.CharField(null=True, blank=True, max_length=255)),
                ('txn_id', models.CharField(null=True, blank=True, max_length=255)),
                ('class_ref', models.CharField(null=True, blank=True, max_length=255)),
                ('city', models.CharField(null=True, blank=True, max_length=255)),
                ('sales_tax_total', models.CharField(null=True, blank=True, max_length=255)),
                ('list_id', models.CharField(null=True, blank=True, max_length=255)),
                ('state', models.CharField(null=True, blank=True, max_length=255)),
                ('edit_sequence', models.CharField(null=True, blank=True, max_length=255)),
                ('time_created', models.CharField(null=True, blank=True, max_length=255)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='QBInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, verbose_name='ID', serialize=False)),
                ('addr1', models.CharField(null=True, blank=True, max_length=255)),
                ('addr3', models.CharField(null=True, blank=True, max_length=255)),
                ('sales_tax_percentage', models.CharField(null=True, blank=True, max_length=255)),
                ('full_name', models.CharField(null=True, blank=True, max_length=255)),
                ('time_modified', models.CharField(null=True, blank=True, max_length=255)),
                ('applied_amount', models.CharField(null=True, blank=True, max_length=255)),
                ('ship_date', models.CharField(null=True, blank=True, max_length=255)),
                ('customer_sales_tax_code_ref', models.CharField(null=True, blank=True, max_length=255)),
                ('po_number', models.CharField(null=True, blank=True, max_length=255)),
                ('addr2', models.CharField(null=True, blank=True, max_length=255)),
                ('item_sales_tax_ref', models.CharField(null=True, blank=True, max_length=255)),
                ('ship_address', models.CharField(null=True, blank=True, max_length=255)),
                ('bill_address', models.CharField(null=True, blank=True, max_length=255)),
                ('txn_number', models.CharField(null=True, blank=True, max_length=255)),
                ('sales_tax_total', models.CharField(null=True, blank=True, max_length=255)),
                ('is_paid', models.CharField(null=True, blank=True, max_length=255)),
                ('suggested_discount_amount', models.CharField(null=True, blank=True, max_length=255)),
                ('ref_number', models.CharField(null=True, blank=True, max_length=255)),
                ('class_ref', models.CharField(null=True, blank=True, max_length=255)),
                ('txn_date', models.CharField(null=True, blank=True, max_length=255)),
                ('addr4', models.CharField(null=True, blank=True, max_length=255)),
                ('postal_code', models.CharField(null=True, blank=True, max_length=255)),
                ('ar_account_ref', models.CharField(null=True, blank=True, max_length=255)),
                ('is_finance_charge', models.CharField(null=True, blank=True, max_length=255)),
                ('is_to_be_printed', models.CharField(null=True, blank=True, max_length=255)),
                ('suggested_discount_date', models.CharField(null=True, blank=True, max_length=255)),
                ('time_created', models.CharField(null=True, blank=True, max_length=255)),
                ('memo', models.CharField(null=True, blank=True, max_length=255)),
                ('terms_ref', models.CharField(null=True, blank=True, max_length=255)),
                ('customer_ref', models.CharField(null=True, blank=True, max_length=255)),
                ('city', models.CharField(null=True, blank=True, max_length=255)),
                ('due_date', models.CharField(null=True, blank=True, max_length=255)),
                ('txn_id', models.CharField(null=True, blank=True, max_length=255)),
                ('balance_remaining', models.CharField(null=True, blank=True, max_length=255)),
                ('subtotal', models.CharField(null=True, blank=True, max_length=255)),
                ('state', models.CharField(null=True, blank=True, max_length=255)),
                ('list_id', models.CharField(null=True, blank=True, max_length=255)),
                ('is_pending', models.CharField(null=True, blank=True, max_length=255)),
                ('edit_sequence', models.CharField(null=True, blank=True, max_length=255)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
    ]
