# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks', '0005_auto_20150206_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageque',
            name='name',
            field=models.CharField(default=b'Query', max_length=2500),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbaccount',
            name='account_number',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbaccount',
            name='account_type',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbaccount',
            name='balance',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbaccount',
            name='cash_flow_classification',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbaccount',
            name='desc',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbaccount',
            name='edit_sequence',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbaccount',
            name='full_name',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbaccount',
            name='is_active',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbaccount',
            name='list_id',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbaccount',
            name='name',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbaccount',
            name='parent_ref',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbaccount',
            name='special_account_type',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbaccount',
            name='sublevel',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbaccount',
            name='time_created',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbaccount',
            name='time_modified',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbaccount',
            name='total_balance',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcheck',
            name='account_ref',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcheck',
            name='addr1',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcheck',
            name='addr2',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcheck',
            name='addr3',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcheck',
            name='addr4',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcheck',
            name='address',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcheck',
            name='amount',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcheck',
            name='city',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcheck',
            name='country',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcheck',
            name='edit_sequence',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcheck',
            name='full_name',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcheck',
            name='is_to_be_printed',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcheck',
            name='list_id',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcheck',
            name='memo',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcheck',
            name='payee_entity_ref',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcheck',
            name='postal_code',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcheck',
            name='ref_number',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcheck',
            name='state',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcheck',
            name='time_created',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcheck',
            name='time_modified',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcheck',
            name='txn_date',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcheck',
            name='txn_id',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcheck',
            name='txn_number',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='account_number',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='addr1',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='addr2',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='addr3',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='addr4',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='alt_contact',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='alt_phone',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='balance',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='bill_address',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='city',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='company_name',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='contact',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='customer_type_ref',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='edit_sequence',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='email',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='fax',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='first_name',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='full_name',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='is_active',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='item_sales_tax_ref',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='job_status',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='last_name',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='list_id',
            field=models.CharField(max_length=2500, unique=True, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='middle_name',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='name',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='notes',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='phone',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='postal_code',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='sales_tax_code_ref',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='salutation',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='ship_address',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='state',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='sublevel',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='terms_ref',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='time_created',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='time_modified',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbcustomer',
            name='total_balance',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbestimate',
            name='addr1',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbestimate',
            name='addr2',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbestimate',
            name='addr3',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbestimate',
            name='addr4',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbestimate',
            name='bill_address',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbestimate',
            name='city',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbestimate',
            name='class_ref',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbestimate',
            name='customer_ref',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbestimate',
            name='customer_sales_tax_code_ref',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbestimate',
            name='due_date',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbestimate',
            name='edit_sequence',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbestimate',
            name='full_name',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbestimate',
            name='item_sales_tax_ref',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbestimate',
            name='list_id',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbestimate',
            name='memo',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbestimate',
            name='postal_code',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbestimate',
            name='ref_number',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbestimate',
            name='sales_tax_percentage',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbestimate',
            name='sales_tax_total',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbestimate',
            name='state',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbestimate',
            name='subtotal',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbestimate',
            name='time_created',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbestimate',
            name='time_modified',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbestimate',
            name='total_amount',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbestimate',
            name='txn_date',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbestimate',
            name='txn_id',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbestimate',
            name='txn_number',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='addr1',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='addr2',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='addr3',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='addr4',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='applied_amount',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='ar_account_ref',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='balance_remaining',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='bill_address',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='city',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='class_ref',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='customer_ref',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='customer_sales_tax_code_ref',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='due_date',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='edit_sequence',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='full_name',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='is_finance_charge',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='is_paid',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='is_pending',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='is_to_be_printed',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='item_sales_tax_ref',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='list_id',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='memo',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='po_number',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='postal_code',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='ref_number',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='sales_tax_percentage',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='sales_tax_total',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='ship_address',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='ship_date',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='state',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='subtotal',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='suggested_discount_amount',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='suggested_discount_date',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='terms_ref',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='time_created',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='time_modified',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='txn_date',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='txn_id',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='qbinvoice',
            name='txn_number',
            field=models.CharField(max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='receiveresponse',
            name='name',
            field=models.CharField(default=b'', max_length=2500, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_file',
            field=models.CharField(default=b'', max_length=2500, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='major_version',
            field=models.CharField(default=b'', max_length=2500, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='minor_version',
            field=models.CharField(default=b'', max_length=2500, blank=True),
            preserve_default=True,
        ),
    ]
